name: "Build and ship package"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "Use appropriate Node.js"
      uses: "actions/setup-node@v3"
      with:
        node-version: "17.0.1"
        cache: 'npm'

    - run: "sudo apt install libpcsclite-dev"

    - run: "npm install"

    - run: "npm run build"

    - name: "Upload package"
      uses: "actions/upload-artifact@v2"
      with:
        name: "package"
        path: "dist/installers/*.deb"

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/installers/*.deb
