name: "Build and ship package"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "Use appropriate Node.js"
      uses: "actions/setup-node@v3"
      with:
        node-version: "14.18.1"
        cache: 'npm'

    - run: "sudo apt install pcscd libpcsclite1 libpcsclite-dev openssl"

    # Install packages, rebuild using electron
    - run: "npm install"
    - run: "npm install @pokusew/pcsclite --build-from-source"
    - run: "./node_modules/.bin/electron-rebuild"

    # Build
    - run: "npm run build-semantic"
    - run: "npm run build"

    # - name: "Upload package"
    #   uses: "actions/upload-artifact@v4"
    #   with:
    #     name: "package"
    #     path: "dist/installers/*.deb"

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/installers/*.deb
