name: "Build and ship package"

on:
  push:
    branches:
      - "maartenberg/ship-on-tag"
      - "development"
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"

    - name: "Use appropriate Node.js"
      uses: "actions/setup-node@v2"
      with:
        node-version: "14.18.1"
        cache: 'npm'

    - run: "sudo apt install libpcsclite-dev"

    - run: "npm install"

    - run: "npm run build"

    - name: "Upload package"
      uses: "actions/upload-artifact@v2"
      with:
        name: "package"
        path: "dist/installers/*.deb"

    - run: "mkdir -p ~/.ssh"
    - run: "echo \"$sshkey\" > ~/.ssh/id_ed25519"
      env:
        sshkey: "${{ secrets.FREIGHT_KEY_PROD }}"

    - run: "chmod 0600 ~/.ssh/id_ed25519"

    - name: "Copy package to server"
      run: "scp -o StrictHostKeyChecking=no dist/installers/*.deb freight@svsticky.nl:/tmp/new_sloth.deb"

    - name: "Add package to freight"
      run: "ssh -o StrictHostKeyChecking=no freight@svsticky.nl <<< 'freight add /tmp/new_sloth.deb apt/focal; freight cache; rm -v /tmp/new_sloth.deb'"
